const pets = [
  { name: 'Louie', breed: 'Long-hair Dachshund', companionId: 1 },
  { name: 'Nemo', breed: 'Tabby Cat ', companionId: 31 },
  { name: 'Hazel', breed: 'German Shepherd/Husky', companionId: 3 },
  { name: 'Riker', breed: 'Tennesee Walking Hound', companionId: 5 },
  { name: 'Hogan', breed: 'Mini Goldendoodle', companionId: 7 },
  { name: 'Benji', breed: 'Maine Coon', companionId: 31 },
  { name: 'Oscar', breed: 'Couch Chewer', companionId: 26 },
  { name: 'Grim', breed: 'Cutest Short Hair Cat', companionId: 2 },
  { name: 'Circuit "Sir Cat"', breed: 'Chunky Orange Boy', companionId: 14 },
  { name: 'JC', breed: 'Ginger', companionId: 10 },
  { name: 'Denali', breed: 'German Shepherd', companionId: 8 },
  { name: 'Milo', breed: 'yellow tabby', companionId: 12 },
  { name: 'Bruce', breed: 'Pitty-mix', companionId: 4 },
  { name: 'Sophie', breed: 'Husky Mix', companionId: 28 },
  { name: 'Mochi', breed: 'straffordshire-mix', companionId: 24 },
  { name: 'Sadie', breed: 'Shar-Pei', companionId: 16 },
  { name: 'Stella', breed: 'Labrador Retriever', companionId: 18 },
  { name: 'Grover', breed: 'Corgi', companionId: 30 },
  { name: 'Cleo', breed: 'Golden Retreiver', companionId: 17 },
  { name: 'Jasmine', breed: 'Golden Retreiver', companionId: 20 },
  { name: 'Zazu', breed: 'Pharaoh Hound', companionId: 21 },
  { name: 'Ash', breed: 'Russian Blue', companionId: 22 },
  { name: 'Sirius', breed: 'One-Eyed Cat', companionId: 11 },
  { name: 'Jtp', breed: 'unknown', companionId: 35 },
  { name: 'Kafka', breed: 'mixed', companionId: 24 },
  { name: 'Bayou', breed: 'Mastiff', companionId: 15 },
  { name: 'Simba', breed: 'Shizzou', companionId: 6 },
  { name: 'Tuna', breed: 'smol cat', companionId: 23 },
  { name: 'Otter', breed: 'Coolest Hamster', companionId: 27 },
  { name: 'turk', breed: 'snapping turtle', companionId: 36 },
  { name: 'Freya', breed: 'Australian Sheperd', companionId: 25 },
  { name: 'Grandpa', breed: 'Schnauzer', companionId: 30 },
  { name: 'Kevin', breed: 'Bearded-Dragon', companionId: 9 },
  { name: 'Carl', breed: 'Whale', companionId: 19 },
  { name: 'Lamont', breed: 'Labradane', companionId: 32 },
  { name: 'Akamaru', breed: 'Great Pyrenees', companionId: 27 },
  { name: 'Astra', breed: 'menace', companionId: 35 },
  { name: 'Myzza', breed: 'cavachon', companionId: 34 },
];

const companions = [
  { name: 'Peter' },
  { name: 'Sean' },
  { name: 'Thomas' },
  { name: 'Matthew' },
  { name: 'Chelsea' },
  { name: 'Kortney' },
  { name: 'Jae' },
  { name: 'Dallin' },
  { name: 'Collin' },
  { name: 'Brandi' },
  { name: 'Philip' },
  { name: 'Moe' },
  { name: 'Rediet' },
  { name: 'Spence' },
  { name: 'Chandler' },
  { name: 'Tyler' },
  { name: 'Jellena' },
  { name: 'Ashley' },
  { name: 'Trenton' },
  { name: 'Jellena2' },
  { name: 'Brandon' },
  { name: 'David' },
  { name: 'Megan' },
  { name: 'Krystle' },
  { name: 'Christopher' },
  { name: 'Adam' },
  { name: 'Anthony' },
  { name: 'Dylan' },
  { name: 'Reza' },
  { name: 'anonymous' },
  { name: 'Kevin' },
  { name: 'Tri' },
  { name: 'Rahmat' },
  { name: 'Kaleef' },
  { name: 'anonymous2' },
  { name: 'anonymous3' },
  { name: 'Avery' },
];

const companionsWithPasswords = companions.map((companion, index) => {
  companion.password = `password${index + 1}`;
  return companion;
});

console.log(companionsWithPasswords);

const tricks = [
  { title: 'clean the dishes' },
  { title: 'fold my clothes' },
  { title: 'Be cute' },
  { title: 'taxes' },
  { title: 'play dead' },
  { title: 'be overly dramatic' },
  { title: 'marvel triva' },
  { title: 'Illusions Michael' },
  { title: 'snoot' },
  { title: 'be a large gentleman' },
  { title: 'roll over' },
  { title: 'be a punk' },
  { title: 'eats worms' },
  { title: 'pee on the bed' },
  { title: 'fart' },
  { title: 'cry all day' },
  { title: 'sleep' },
  { title: 'steal stuff and open doors' },
  { title: 'shake' },
  { title: 'get mad' },
  { title: 'bark to command "Dracarys"' },
  { title: 'find socks' },
  { title: 'BackFlip' },
  { title: 'puts treat on nose "wait"' },
  { title: 'bark at nothing' },
  { title: 'testing the beds' },
  { title: 'Fly' },
  { title: 'get me taco bell' },
  { title: 'CPR' },
  { title: 'wake me up at 3am' },
  { title: "Drop it like it's hot" },
  { title: 'super zoomies' },
  { title: 'eat while laying down' },
  { title: 'unlimited fetches' },
  { title: 'be big' },
  { title: 'designated driver' },
  { title: 'delusions of granduer' },
  { title: 'eat' },
  { title: 'gib leaf' },
  { title: 'Fang over Fang' },
  { title: 'scream for food' },
  { title: 'step on lung to stop my breathing' },
  { title: 'mlem checks' },
];

const petTricks = [
  { petId: 2, trickId: 3 },
  { petId: 2, trickId: 31 },
  { petId: 2, trickId: 14 },
  { petId: 3, trickId: 6 },
  { petId: 3, trickId: 3 },
  { petId: 3, trickId: 5 },
  { petId: 3, trickId: 9 },
  { petId: 3, trickId: 25 },
  { petId: 3, trickId: 35 },
  { petId: 3, trickId: 38 },
  { petId: 4, trickId: 17 },
  { petId: 4, trickId: 19 },
  { petId: 4, trickId: 15 },
  { petId: 4, trickId: 12 },
  { petId: 4, trickId: 6 },
  { petId: 5, trickId: 3 },
  { petId: 5, trickId: 9 },
  { petId: 5, trickId: 11 },
  { petId: 5, trickId: 12 },
  { petId: 5, trickId: 17 },
  { petId: 5, trickId: 22 },
  { petId: 5, trickId: 32 },
  { petId: 6, trickId: 30 },
  { petId: 6, trickId: 3 },
  { petId: 6, trickId: 2 },
  { petId: 8, trickId: 3 },
  { petId: 8, trickId: 17 },
  { petId: 9, trickId: 10 },
  { petId: 9, trickId: 41 },
  { petId: 9, trickId: 42 },
  { petId: 10, trickId: 37 },
  { petId: 10, trickId: 7 },
  { petId: 10, trickId: 15 },
  { petId: 11, trickId: 3 },
  { petId: 11, trickId: 5 },
  { petId: 11, trickId: 9 },
  { petId: 11, trickId: 11 },
  { petId: 11, trickId: 17 },
  { petId: 11, trickId: 19 },
  { petId: 11, trickId: 24 },
  { petId: 11, trickId: 35 },
  { petId: 12, trickId: 12 },
  { petId: 12, trickId: 17 },
  { petId: 12, trickId: 16 },
  { petId: 12, trickId: 37 },
  { petId: 12, trickId: 30 },
  { petId: 12, trickId: 3 },
  { petId: 12, trickId: 20 },
  { petId: 12, trickId: 14 },
  { petId: 13, trickId: 15 },
  { petId: 13, trickId: 16 },
  { petId: 13, trickId: 25 },
  { petId: 14, trickId: 34 },
  { petId: 14, trickId: 17 },
  { petId: 14, trickId: 18 },
  { petId: 14, trickId: 9 },
  { petId: 15, trickId: 18 },
  { petId: 15, trickId: 20 },
  { petId: 15, trickId: 41 },
  { petId: 15, trickId: 6 },
  { petId: 15, trickId: 3 },
  { petId: 15, trickId: 43 },
  { petId: 17, trickId: 25 },
  { petId: 17, trickId: 4 },
  { petId: 17, trickId: 7 },
  { petId: 17, trickId: 18 },
  { petId: 17, trickId: 17 },
  { petId: 17, trickId: 34 },
  { petId: 17, trickId: 19 },
  { petId: 17, trickId: 6 },
  { petId: 18, trickId: 3 },
  { petId: 18, trickId: 6 },
  { petId: 18, trickId: 7 },
  { petId: 18, trickId: 9 },
  { petId: 18, trickId: 11 },
  { petId: 19, trickId: 32 },
  { petId: 19, trickId: 22 },
  { petId: 19, trickId: 6 },
  { petId: 20, trickId: 32 },
  { petId: 20, trickId: 23 },
  { petId: 21, trickId: 3 },
  { petId: 21, trickId: 6 },
  { petId: 21, trickId: 11 },
  { petId: 21, trickId: 12 },
  { petId: 21, trickId: 17 },
  { petId: 21, trickId: 21 },
  { petId: 21, trickId: 32 },
  { petId: 22, trickId: 23 },
  { petId: 22, trickId: 6 },
  { petId: 23, trickId: 15 },
  { petId: 23, trickId: 17 },
  { petId: 23, trickId: 30 },
  { petId: 23, trickId: 12 },
  { petId: 23, trickId: 16 },
  { petId: 25, trickId: 33 },
  { petId: 25, trickId: 35 },
  { petId: 25, trickId: 17 },
  { petId: 25, trickId: 3 },
  { petId: 25, trickId: 43 },
  { petId: 25, trickId: 10 },
  { petId: 26, trickId: 17 },
  { petId: 26, trickId: 15 },
  { petId: 26, trickId: 6 },
  { petId: 26, trickId: 35 },
  { petId: 26, trickId: 38 },
  { petId: 26, trickId: 3 },
  { petId: 27, trickId: 5 },
  { petId: 27, trickId: 19 },
  { petId: 27, trickId: 16 },
  { petId: 27, trickId: 11 },
  { petId: 27, trickId: 27 },
  { petId: 27, trickId: 31 },
  { petId: 27, trickId: 39 },
  { petId: 27, trickId: 29 },
  { petId: 29, trickId: 29 },
  { petId: 29, trickId: 3 },
  { petId: 29, trickId: 18 },
  { petId: 29, trickId: 31 },
  { petId: 29, trickId: 12 },
  { petId: 31, trickId: 31 },
  { petId: 31, trickId: 17 },
  { petId: 31, trickId: 25 },
  { petId: 32, trickId: 18 },
  { petId: 32, trickId: 25 },
  { petId: 32, trickId: 26 },
  { petId: 33, trickId: 13 },
  { petId: 33, trickId: 35 },
  { petId: 34, trickId: 4 },
  { petId: 34, trickId: 10 },
  { petId: 34, trickId: 15 },
  { petId: 34, trickId: 21 },
  { petId: 34, trickId: 29 },
  { petId: 34, trickId: 31 },
  { petId: 35, trickId: 1 },
  { petId: 35, trickId: 2 },
  { petId: 35, trickId: 3 },
  { petId: 35, trickId: 6 },
  { petId: 35, trickId: 12 },
  { petId: 35, trickId: 14 },
  { petId: 35, trickId: 15 },
  { petId: 35, trickId: 16 },
  { petId: 35, trickId: 19 },
  { petId: 35, trickId: 28 },
  { petId: 35, trickId: 30 },
  { petId: 36, trickId: 40 },
  { petId: 36, trickId: 36 },
  { petId: 36, trickId: 27 },
  { petId: 36, trickId: 23 },
  { petId: 36, trickId: 41 },
  { petId: 38, trickId: 17 },
  { petId: 38, trickId: 26 },
];

module.exports = {
  pets,
  companionsWithPasswords,
  tricks,
  petTricks,
};
